services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    env_file:
      - path: .env
        required: false
    environment:
      - PYTHONUNBUFFERED=1
